name: Release
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: ${{ github.event.repository.name }}
      # The logic below handles the npm publication:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@benddao'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_PACKAGES_REGISTRY_READ_ONLY }}
      - uses: actions/cache@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup yarn
        if: ${{ steps.release.outputs.release_created }}
        run: npm install -g yarn
      - name: Setup Nodejs with yarn caching
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: yarn
      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_PACKAGES_REGISTRY_READ_ONLY }}
      - run: npm run ci:test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_PACKAGES_REGISTRY_READ_ONLY }}
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
